services:
  - type: web
    name: lms-backend
    env: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/lms-backend-0.0.1-SNAPSHOT.jar
    plan: free
